name: Update Branches

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Fetch all branches
      run: git fetch --all

    - name: Merge main into branches
      run: |
        branches=("python" "java" "cpp" "javascript")
        for branch in "${branches[@]}"; do
          git checkout $branch
          git merge main --allow-unrelated-histories
          if [ $? -eq 0 ]; then
            echo "Successfully merged new questions into $branch"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $branch
          else
            echo "Merge conflict in $branch. Please resolve manually."
            exit 1
          fi
        done

    - name: Checkout main again
      run: git checkout main
