name: Update Branches

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Fetch all branches
      run: git fetch --all

    - name: Merge main into branches
      run: |
        branches=("python" "C" "C#" "C++" "java" "javascript")
        for branch in "${branches[@]}"; do
          git checkout $branch
          git merge --no-commit main --allow-unrelated-histories

          # Restore .github/workflows directory to its original state
          git restore --source=$branch --staged --worktree -- .github/workflows/

          # Force replace README.md files and handle conflicts
          for file in README.md; do
            if git ls-files --error-unmatch $file > /dev/null 2>&1; then
              git checkout main -- $file
              git add $file
            fi
          done

          # Resolve conflicts in other files
          if git status --porcelain | grep -q "CONFLICT"; then
            echo "Conflicts found, resolving by using the version from main for conflicted files"
            
            # Resolve conflicts by keeping files from the main branch
            git diff --name-only --diff-filter=U | while read -r conflicted_file; do
              echo "Resolving conflict in $conflicted_file by using main's version"
              git checkout main -- "$conflicted_file"
              git add "$conflicted_file"
            done
            
            git commit -m "Resolve conflicts and replace conflicted files with versions from main"
          else
            # Commit if no conflicts
            git commit -m "Merge main into $branch with forced replacement of README.md files"
          fi

          # Push changes
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $branch || exit 0
        done

    - name: Checkout main again
      run: git checkout main
