name: Update Branches

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Fetch all branches
      run: git fetch --all

    - name: Merge main into branches
      run: |
        branches=("python" "C" "C#" "C++" "java" "javascript")
        for branch in "${branches[@]}"; do
          git checkout $branch
          git merge --no-commit main --allow-unrelated-histories

          # Restore .github/workflows directory to its original state
          git restore --source=$branch --staged --worktree -- .github/workflows/

          # Force replace .README files
          git checkout main -- *.README

          # Resolve conflicts by keeping the version from main
          git add *.README
          git commit -m "Merge main into $branch with forced replacement of .README files"
          
          # Push changes
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $branch
        done

    - name: Checkout main again
      run: git checkout main
