name: Update Branches

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Fetch all branches
      run: git fetch --all

    - name: Merge main into branches
      run: |
        branches=("python" "C" "C#" "C++" "java" "javascript")
        for branch in "${branches[@]}"; do
          git checkout $branch
          git merge --no-commit main --allow-unrelated-histories

          # Restore .github/workflows directory to its original state
          git restore --source=$branch --staged --worktree -- .github/workflows/

          # Force replace README.md files and handle conflicts
          for file in README.md; do
            if git ls-files --error-unmatch $file > /dev/null 2>&1; then
              git checkout main -- $file
              git add $file
            fi
          done

          # Check for merge conflicts and resolve them
          if git ls-files -u | grep -q "README.md"; then
            echo "Conflicts found in README.md, resolving by using the version from main"
            git checkout main -- README.md
            git add README.md
            git commit -m "Resolve conflicts and replace README.md files from main"
          else
            # Commit if no conflicts
            git commit -m "Merge main into $branch with forced replacement of README.md files"
          fi

          # Push changes
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $branch || exit 0
        done

    - name: Checkout main again
      run: git checkout main
